apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-scanner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/buddemax/codescanner.git'
    path: 'k8s'                # ← hier liegt argo-app.yaml und deine Manifeste
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
