apiVersion: v1
kind: Service
metadata:
  name: code-scanner-backend-svc
spec:
  type: LoadBalancer                # ← hier umstellen
  selector:
    app: code-scanner-backend
  ports:
    - name: http
      port: 8000                    # Port auf localhost
      targetPort: 8000              # Port im Container
      protocol: TCP
