apiVersion: v1
kind: Service
metadata:
  name: code-scanner-backend
  labels:
    app: code-scanner-backend
spec:
  selector:
    app: code-scanner-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP 