apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-scanner
  template:
    metadata:
      labels:
        app: code-scanner
    spec:
      containers:
        - name: code-scanner
          image: ghcr.io/buddemax/codescanner:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000