apiVersion: v1
kind: Service
metadata:
  name: code-scanner-svc
spec:
  type: LoadBalancer
  selector:
    app: code-scanner
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
