# .github/workflows/deploy.yml
name: Deploy Next.js

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Abhängigkeiten installieren & Build
        run: |
          npm ci
          npm run build


