# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and sind governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy Security Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '25 18 * * 1'

permissions:
  contents: read

jobs:
  trivy-scan:
    name: Trivy Security Checks
    runs-on: ubuntu-latest

    # Erforderlich für SARIF-Upload
    permissions:
      contents: read
      security-events: write
      actions: read

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- FS-Scan (Code + Dependencies + Secrets) ----------
      - name: FS scan (Schwachstellen & Secrets)
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 0
          format: sarif
          output: trivy-fs.sarif

      # ---------- Docker-Image bauen ----------
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      # ---------- Image-Scan (Container-Schwachstellen) ----------
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          # SARIF-Template aus dem Repo
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          severity: 'CRITICAL,HIGH'

      # ---------- IaC-Scan (K8s-Manifeste & Dockerfile) ----------
      - name: IaC scan (K8s + Dockerfile)
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: config
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 0
          format: sarif
          output: trivy-config.sarif

      # ---------- SARIF-Ergebnisse hochladen ----------
      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif

      - name: Upload Trivy container scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Upload Trivy config scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-config.sarif
