# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and sind governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy Security Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '25 18 * * 1'

permissions:
  contents: read

jobs:
  trivy-scan:
    name: Trivy Security Checks
    runs-on: ubuntu-latest

    # Erforderlich für SARIF-Upload
    permissions:
      contents: read
      security-events: write
      actions: read

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- FS-Scan (Code + Dependencies + Secrets) ----------
      - name: FS scan (Schwachstellen & Secrets)
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 0
          format: sarif
          output: trivy-fs.sarif

      # ---------- Docker-Images bauen ----------
      - name: Build frontend image
        run: |
          docker build -t docker.io/my-organization/frontend:${{ github.sha }} ./frontend

      - name: Build backend image
        run: |
          docker build -t docker.io/my-organization/backend:${{ github.sha }} ./backend

      # ---------- Image-Scan (Container-Schwachstellen) ----------
      - name: Run Trivy vulnerability scanner for frontend
        uses: aquasecurity/trivy-action@77137e9dc3ab1b329b7c8a38c2eb7475850a14e8
        with:
          image-ref: 'docker.io/my-organization/frontend:${{ github.sha }}'
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-frontend-results.sarif
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner for backend
        uses: aquasecurity/trivy-action@77137e9dc3ab1b329b7c8a38c2eb7475850a14e8
        with:
          image-ref: 'docker.io/my-organization/backend:${{ github.sha }}'
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-backend-results.sarif
          severity: 'CRITICAL,HIGH'

      # ---------- IaC-Scan (K8s-Manifeste & Dockerfile) ----------
      - name: IaC scan (K8s + Dockerfile)
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: config
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 0
          format: sarif
          output: trivy-config.sarif

      # ---------- SARIF-Ergebnisse hochladen ----------
      - name: Upload Trivy filesystem scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs-scan

      - name: Upload Trivy frontend container scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-frontend-results.sarif
          category: trivy-frontend-container-scan

      - name: Upload Trivy backend container scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-backend-results.sarif
          category: trivy-backend-container-scan

      - name: Upload Trivy config scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-config.sarif
          category: trivy-config-scan
