# .github/workflows/secure.yml
name: Trivy Security Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: 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

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code-inspector
        uses: actions/checkout@v4
        with:
          repository: CozyBrozy/code-inspector
          token: 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
          path: code-inspector

      - name: FS scan (Schwachstellen & Secrets)
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: fs
          scan-ref: code-inspector
          severity: CRITICAL,HIGH
          exit-code: 1
          format: sarif
          output: trivy-fs.sarif

      - name: Build Docker Image for code-inspector
        run: |
          docker build -t ghcr.io/CozyBrozy/code-inspector:${{ github.sha }} code-inspector

      - name: Image scan (Container-Schwachstellen)
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: image
          image-ref: ghcr.io/CozyBrozy/code-inspector:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 1
          format: sarif
          output: trivy-image.sarif

      - name: IaC scan (K8s + Dockerfile)
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: config
          scan-ref: code-inspector/k8s
          severity: CRITICAL,HIGH
          exit-code: 1
          format: sarif
          output: trivy-config.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            trivy-fs.sarif
            trivy-image.sarif
            trivy-config.sarif
